### ISSUE TITLE
User Profile Update

### ISSUE THREAD

**Issue by changhengliou** [DarkBruce/sprint2021-team-2-repo#10]
### User Story
​
As a user, I want to be able to update my profile's info. 
​
### Acceptance Criteria
​
Users should be able to update their profiles through a profile page.

**Definition of Done**
1. When a user creates an update to their profile, it should be persisted in the user model and they should be able to see it in their account if they are logged in.
2. Any updates would only be persisted once the user clicks save changes and they are valid changes.

**Comment by DarkBruce** [comment]
The profile update form doesn't work when the form isn't filled competely. Will improve in the future
