### ISSUE TITLE
Integrate User Model (distinct fields)

### ISSUE THREAD

**Issue by changhengliou** [DarkBruce/sprint2021-team-2-repo#6]
### User Story

As a user, I want to have some of my basic info (e.g., phone number, address) included in my profile to facilitate other usage (e.g., restaurants recommendation) of this system.
​
### Acceptance Criteria

User model should include basic info such as name, phone number, address, etc

**Comment by DarkBruce** [comment]
This issue is closed since it's same with [https://github.com/DarkBruce/sprint2021-team-2-repo/issues/13](url).
