### ISSUE TITLE
Handle error when user not logged in tries to leave review

### ISSUE THREAD

**Issue by ahmed1** [DarkBruce/sprint2021-team-2-repo#63]
when user not logged in tries to leave review, they get 500 server error. Should just give message they can't leave review or remove button for them

**Comment by DarkBruce** [comment]
Resolved in this commit [https://github.com/DarkBruce/sprint2021-team-2-repo/commit/5eacab09bfd97a027f438d8e8a945f65cac770d9](url)

Now guest users who try to leave review shall be redirected to the same page with a warning says that **"Please login before making review"**.
