### ISSUE TITLE
As an admin, I want to view the reported reviews/comments from a management page that can only accessed by admin

### ISSUE THREAD

**Issue by YuhanChen8789** [DarkBruce/sprint2021-team-2-repo#81]
**User story**
As an admin, I want to view the reported reviews/comments from a management page that can only be accessed by the admin.
**Acceptance criteria**
When admin logged in, they can view the reported reviews/comments from a management page.
**Definition of Done**
The management page can be shown properly on the production instance with all the reported reviews/comments correctly displayed.

**Frontend**
create a management page as a template that enables view/hide/delete

**Backend**

**Comment by DarkBruce** [comment]
- Modify the frontend view to be a simpler table view for admins.
- Add a **ignore** button to simply delete the invalid report ticket.
